import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const geistSans = Lato({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased bg-[#F3F4F6]`}>
        {children}
      </body>
    </html>
  );
}
